t

diff --git a/.github/workflows/deploy-terraform.yml b/.github/workflows/deploy-terraform.yml
--- a/.github/workflows/deploy-terraform.yml
+++ b/.github/workflows/deploy-terraform.yml
@@ -30,7 +30,6 @@ jobs:
 
     env:
       PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
-      GOOGLE_CREDENTIALS: ${{ secrets.TF_SA }}
 
     steps:
 
@@ -44,29 +43,23 @@ jobs:
         uses: google-github-actions/auth@v2
         with:
           credentials_json: '${{ secrets.TF_SA }}' 
-
-      - name: Debug Auth Output
-        run: |
-          echo "Credential file: $GOOGLE_APPLICATION_CREDENTIALS"
-          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
-            echo "Credential file exists"
-          else
-            echo "Credential file not found!"
-            exit 1
-          fi
+          export_environment_variables: true
           
       - name: Set up Google Cloud
         uses: google-github-actions/setup-gcloud@v2
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
 
-      - name: Test gcloud command
+      - name: Test GCloud auth sji tidy
         run: |
-          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
-          gcloud kms keyrings describe data-store-keyring-uat --location europe-west2
-        env:
-          GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS      
-        #should we allow injection? 
+          echo "Checking credentials file at: $GOOGLE_APPLICATION_CREDENTIALS"
+          if [ ! -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
+            echo "❌ Credentials file missing!"
+            exit 1
+          fi
+          gcloud kms keyrings describe data-store-keyring-uat \
+            --location europe-west2 \
+            --project $PROJECT_ID
 
       - name: Terraform Quality Check
         uses: ./.github/actions/terraform/quality
